# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
resources:
  repositories:
      - repository: template
        name: template
        type: git
         
        
trigger:
- master

stages:
- stage: Initial_Job
  displayName: 'Code Pull'
  jobs:
  - job: 'Initial_Job'
    steps:
    - checkout: none



########################################################################    
- stage: Build
  displayName: Application Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: windows-latest

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install 
        npm install jasmine-node
        npm run build --if-present
        npm test
      displayName: 'npm install and build'
#####################################################################

- stage: WhiteSource_Bolt
  displayName: WhiteSource_Testing
  dependsOn: Initial_Job
  condition: succeeded()
  jobs:
  - job: 'Testing'
    steps:
       - task: WhiteSource@21
         inputs:
          cwd: '$(System.DefaultWorkingDirectory)'
          projectName: 'Testing-Vynchronize'

###############################################################################


- stage: Archive
  displayName: ArchiveFiles
  jobs:
  - job: Archive
    displayName: Archive
    steps:
    - task: ArchiveFiles@2
      inputs:
          rootFolderOrFile: '$(system.defaultworkingdirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
##################################################################
- stage: Unit_Test
  displayName: 'Run Unit Testing'
  jobs:
    - template: node.yml@template
      parameters:
          customCommand: 'test'
       







 
   


      



    


##########################################################################
